
//Introduction to .NET framework
//.NET framework architecture :
// It is layered architecture consisting of several components such as:

//Common type system : Every types in .NET framework is defined in a common
//type system which provides a standard way of defining and using types across
//different programming languages. ex C#, VB.NET, F# etc
//Integer is defined in C# and also in VB.NET, but they are both represented as the same type in the common type system.
//This allows for seamless interoperability between different programming languages in the .NET framework.
//int in C# has same memoery layout and behavior as Integer in VB.NET,
//so they can be used interchangeably when working with .NET framework.

//Common language specification :
//This a a set of rules and guidelines that define how programming languages should be designed and implemented to be compatible with the .NET framework. It ensures that different programming languages can work together seamlessly within the .NET framework. For example, if a programming language supports the common language specification, it can be used to create libraries and components that can be consumed by other
//programming languages that also support the common language specification.
//ex C# and VB.NET both support the common language specification,
//so you can create a library in C# and use it in a VB.NET application without any issues.
//Common language runtime( IMPORTANT) :
//CLR is the most important run time execution environment in the .NET framework. It provides a managed execution environment for .NET applications, which means that it handles memory management, security, and other aspects of application execution.
//The CLR also provides a just-in-time (JIT) compiler that compiles the intermediate language (IL) code generated by the .NET compiler into native machine code that can be executed by the operating system.
//This allows for improved performance and efficiency when running .NET applications. 
//Some common fucntionality of CLR include:
//1. Memory management : CLR manages memory allocation and deallocation for .NET applications, which helps to prevent memory leaks and other memory-related issues.
//2. Security : CLR provides a security model that allows developers to specify permissions and access levels for their applications, which helps to protect against unauthorized access and other security threats.
//3. Exception handling : CLR provides a robust exception handling mechanism that allows developers to handle errors and exceptions in a consistent and reliable way.
//4. Interoperability : CLR allows for seamless interoperability between different programming languages and platforms, which makes it easier for developers to create applications that can run on a variety of devices and operating systems.

//Base class library
//The base class library (BCL) is a collection of pre-built classes and functions that are included with the .NET framework.
//It provides a wide range of functionality for developers,
//including support for data access, networking, security, and more.


//https://github.com/Indranil02/Wipro-NGA-Training_FS_cSharp.git

//Before Starting with Array in C# we shoul should have some basic 
//understanding of below demo :
//Demo 1: Hello world in C#
//Demo 2: Creating a class and object in C#
//Demo 3: Create a class with fields, methods and constructor in C# where we have created a 
//Student class with fields Name and Id, a method DisplayInfo to display the information of 
//the student, and a constructor to initialize the fields of the class. We have also created 
//two objects of the Student class and called the DisplayInfo method to show their information. 
//We have also updated the name and id of the students using UpdateName and UpdateId methods 
//and displayed the updated information.
//Dem0 4: Boxing and Unboxing in C# where we have demonstrated the concept of boxing and 
//unboxing in C#. We have created a value type variable of type int, boxed it into an object, 
//and then unboxed it back to an int variable. We have also shown the type of the object and 
//the unboxed variable to demonstrate the difference between value types and reference types in C#.
//Demo 5: different types of data types in C# where we have discussed 
//the different types of data types in C#, including value types and reference types.
// We have also explained the concept of string as a reference type that behaves like a value type due to its immutability. We have also introduced the StringBuilder class as a mutable string class that allows for efficient string manipulation.
